# Generated by Django 3.1 on 2020-08-14 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousereceipt',
            name='warehouse',
            field=models.ForeignKey(default='b906e3c7-7e5b-4a3f-834e-adcd42da2c6a', on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='salam.firm', verbose_name='Warehouse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehousereceipt',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firm', to='salam.firm', verbose_name='Firm'),
        ),
    ]
