# Generated by Django 3.0.8 on 2020-07-21 13:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('salam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='commodity',
            field=models.CharField(choices=[('CL', 'Crude Oil'), ('ZC', 'Corn'), ('ZS', 'Soybeans'), ('ZW', 'SRW Wheat'), ('KC', 'HRW Wheat'), ('GC', 'Gold'), ('SI', 'Silver'), ('HG', 'Copper'), ('PL', 'Platinum')], max_length=2, verbose_name='Commodity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
