# Generated by Django 3.1 on 2020-08-14 11:48

import apps.salam.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salam', '0002_auto_20200814_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='type',
            field=models.CharField(choices=[('WRHS', 'Warehouse'), ('PROD', 'Producer'), ('CONS', 'Consumer'), ('TRAD', 'TRADER')], default='TRAD', max_length=4, verbose_name='Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehousereceipt',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='salam.firm', validators=[apps.salam.validators.validate_is_warehouse], verbose_name='Warehouse'),
        ),
    ]
