# Generated by Django 3.0.8 on 2020-07-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salam', '0002_auto_20200721_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name_plural': 'Parties'},
        ),
    ]
