# Generated by Django 3.1 on 2020-08-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salam', '0003_auto_20200814_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='type',
            field=models.CharField(choices=[('WRHS', 'Warehouse'), ('PROD', 'Producer'), ('CONS', 'Consumer'), ('TRAD', 'Trader')], max_length=4, verbose_name='Type'),
        ),
    ]
