# Generated by Django 3.0.8 on 2020-07-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salam', '0004_order_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='side',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], editable=False, max_length=4, verbose_name='Trade Side'),
        ),
    ]
