# Generated by Django 3.1 on 2020-08-14 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salam', '0004_auto_20200814_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='warehousereceipt',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firm', to='salam.firm', verbose_name='Firm'),
        ),
    ]
