# Generated by Django 3.1 on 2020-08-15 12:25

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('salam', '0005_auto_20200814_0859'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='warehousereceipt',
            constraint=models.CheckConstraint(check=models.Q(firm=django.db.models.expressions.F('warehouse')),
                                              name='firm_ne_warehouse'),
        ),
    ]
