# Generated by Django 3.1 on 2020-08-17 14:35

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('salam', '0006_auto_20200815_0825'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='warehousereceipt',
            managers=[
                ('receipts', django.db.models.manager.Manager()),
            ],
        ),
    ]
