# Generated by Django 3.0.8 on 2020-07-26 14:41

from django.db import migrations, models
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('salam', '0006_auto_20200721_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'get_latest_by': 'order_time', 'ordering': ['filled', '-order_time']},
        ),
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('bidask', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('MRKT', 'Market'), ('LMT', 'Limit')], default='MRKT', max_length=4, verbose_name='Order Type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UID'),
        ),
        migrations.AlterField(
            model_name='party',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UID'),
        ),
    ]
