# Generated by Django 3.0.8 on 2020-07-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salam', '0007_auto_20200726_1041'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
            ],
        ),
    ]
