# Generated by Django 3.0.8 on 2020-07-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salam', '0008_auto_20200726_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity_filled',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
        ),
    ]
