# Generated by Django 3.0.8 on 2020-07-28 23:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('salam', '0009_order_quantity_filled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'get_latest_by': 'order_time', 'ordering': ['-order_time']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='filled',
        ),
        migrations.AlterField(
            model_name='order',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salam.Party', verbose_name='Party'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity_filled',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity Filled'),
        ),
        migrations.CreateModel(
            name='WarehouseReceipt',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('commodity', models.CharField(choices=[('CL', 'Crude Oil'), ('ZC', 'Corn'), ('ZS', 'Soybeans'), ('ZW', 'SRW Wheat'), ('KC', 'HRW Wheat'), ('GC', 'Gold'), ('SI', 'Silver'), ('HG', 'Copper'), ('PL', 'Platinum')], max_length=2, verbose_name='Commodity')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salam.Party', verbose_name='Party')),
            ],
        ),
    ]
