# Generated by Django 3.0.8 on 2020-07-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salam', '0010_auto_20200728_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contract',
            field=models.CharField(choices=[('N20', 'Jul 2020'), ('Q20', 'Aug 2020'), ('U20', 'Sep 2020'), ('V20', 'Oct 2020'), ('X20', 'Nov 2020'), ('Z20', 'Dec 2020'), ('F21', 'Jan 2021'), ('G21', 'Feb 2021'), ('H21', 'Mar 2021'), ('J21', 'Apr 2021'), ('K21', 'May 2021'), ('M21', 'Jun 2021'), ('N22', 'Jul 2022'), ('Q22', 'Aug 2022'), ('U22', 'Sep 2022'), ('V22', 'Oct 2022'), ('X22', 'Nov 2022'), ('Z22', 'Dec 2022'), ('F23', 'Jan 2023'), ('G23', 'Feb 2023'), ('H23', 'Mar 2023'), ('J23', 'Apr 2023'), ('K23', 'May 2023'), ('M23', 'Jun 2023')], default='Z20', max_length=4, verbose_name='Contract'),
            preserve_default=False,
        ),
    ]
