# Generated by Django 3.0.8 on 2020-07-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salam', '0011_order_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='commodity',
            field=models.CharField(choices=[('CL', 'Crude Oil'), ('ZC', 'Corn'), ('ZS', 'Soybeans'), ('ZW', 'SRW Wheat'), ('KC', 'HRW Wheat'), ('HG', 'Copper'), ('PL', 'Platinum')], max_length=2, verbose_name='Commodity'),
        ),
        migrations.AlterField(
            model_name='warehousereceipt',
            name='commodity',
            field=models.CharField(choices=[('CL', 'Crude Oil'), ('ZC', 'Corn'), ('ZS', 'Soybeans'), ('ZW', 'SRW Wheat'), ('KC', 'HRW Wheat'), ('HG', 'Copper'), ('PL', 'Platinum')], max_length=2, verbose_name='Commodity'),
        ),
    ]
