# Generated by Django 3.0.8 on 2020-08-02 15:00

import apps.salam.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('salam', '0012_auto_20200730_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contract',
            field=models.CharField(choices=[('Q20', 'Aug 2020'), ('U20', 'Sep 2020'), ('V20', 'Oct 2020'), ('X20', 'Nov 2020'), ('Z20', 'Dec 2020'), ('F21', 'Jan 2021'), ('G21', 'Feb 2021'), ('H21', 'Mar 2021'), ('J21', 'Apr 2021'), ('K21', 'May 2021'), ('M21', 'Jun 2021'), ('N21', 'Jul 2021'), ('Q22', 'Aug 2022'), ('U22', 'Sep 2022'), ('V22', 'Oct 2022'), ('X22', 'Nov 2022'), ('Z22', 'Dec 2022'), ('F23', 'Jan 2023'), ('G23', 'Feb 2023'), ('H23', 'Mar 2023'), ('J23', 'Apr 2023'), ('K23', 'May 2023'), ('M23', 'Jun 2023'), ('N23', 'Jul 2023')], max_length=4, validators=[apps.salam.validators.validate_contract_code], verbose_name='Contract'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UID')),
                ('fill_time', models.DateTimeField(auto_now_add=True, verbose_name='Fill Time')),
                ('commodity', models.CharField(choices=[('CL', 'Crude Oil'), ('ZC', 'Corn'), ('ZS', 'Soybeans'), ('ZW', 'SRW Wheat'), ('KC', 'HRW Wheat'), ('HG', 'Copper'), ('PL', 'Platinum')], max_length=2, verbose_name='Commodity')),
                ('contract', models.CharField(max_length=4, validators=[apps.salam.validators.validate_contract_code], verbose_name='Contract')),
                ('price', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Price')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('long_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='long_party', to='salam.Party', verbose_name='Long Party')),
                ('short_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_party', to='salam.Party', verbose_name='Short Party')),
            ],
            options={
                'ordering': ['-fill_time', 'commodity', 'contract'],
                'get_latest_by': 'fill_time',
            },
        ),
    ]
