# Generated by Django 3.0.8 on 2020-08-07 10:38

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('salam', '0013_auto_20200802_1100'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
                ('transactions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='fill_in_one',
            field=models.BooleanField(default=False, verbose_name='Fill In One'),
        ),
    ]
