# Generated by Django 3.1 on 2020-08-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salam', '0014_auto_20200807_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
